/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPassiveIncomeStreams2026RouteImport } from './routes/blog.passive-income-streams-2026'
import { Route as BlogMaximizeWebsiteEarningsAdNetworksRouteImport } from './routes/blog.maximize-website-earnings-ad-networks'
import { Route as BlogFlippingWebsitesBeginnersGuideRouteImport } from './routes/blog.flipping-websites-beginners-guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPassiveIncomeStreams2026Route =
  BlogPassiveIncomeStreams2026RouteImport.update({
    id: '/blog/passive-income-streams-2026',
    path: '/blog/passive-income-streams-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMaximizeWebsiteEarningsAdNetworksRoute =
  BlogMaximizeWebsiteEarningsAdNetworksRouteImport.update({
    id: '/blog/maximize-website-earnings-ad-networks',
    path: '/blog/maximize-website-earnings-ad-networks',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFlippingWebsitesBeginnersGuideRoute =
  BlogFlippingWebsitesBeginnersGuideRouteImport.update({
    id: '/blog/flipping-websites-beginners-guide',
    path: '/blog/flipping-websites-beginners-guide',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/flipping-websites-beginners-guide': typeof BlogFlippingWebsitesBeginnersGuideRoute
  '/blog/maximize-website-earnings-ad-networks': typeof BlogMaximizeWebsiteEarningsAdNetworksRoute
  '/blog/passive-income-streams-2026': typeof BlogPassiveIncomeStreams2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/flipping-websites-beginners-guide': typeof BlogFlippingWebsitesBeginnersGuideRoute
  '/blog/maximize-website-earnings-ad-networks': typeof BlogMaximizeWebsiteEarningsAdNetworksRoute
  '/blog/passive-income-streams-2026': typeof BlogPassiveIncomeStreams2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/flipping-websites-beginners-guide': typeof BlogFlippingWebsitesBeginnersGuideRoute
  '/blog/maximize-website-earnings-ad-networks': typeof BlogMaximizeWebsiteEarningsAdNetworksRoute
  '/blog/passive-income-streams-2026': typeof BlogPassiveIncomeStreams2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/flipping-websites-beginners-guide'
    | '/blog/maximize-website-earnings-ad-networks'
    | '/blog/passive-income-streams-2026'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/flipping-websites-beginners-guide'
    | '/blog/maximize-website-earnings-ad-networks'
    | '/blog/passive-income-streams-2026'
  id:
    | '__root__'
    | '/'
    | '/blog/flipping-websites-beginners-guide'
    | '/blog/maximize-website-earnings-ad-networks'
    | '/blog/passive-income-streams-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogFlippingWebsitesBeginnersGuideRoute: typeof BlogFlippingWebsitesBeginnersGuideRoute
  BlogMaximizeWebsiteEarningsAdNetworksRoute: typeof BlogMaximizeWebsiteEarningsAdNetworksRoute
  BlogPassiveIncomeStreams2026Route: typeof BlogPassiveIncomeStreams2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/passive-income-streams-2026': {
      id: '/blog/passive-income-streams-2026'
      path: '/blog/passive-income-streams-2026'
      fullPath: '/blog/passive-income-streams-2026'
      preLoaderRoute: typeof BlogPassiveIncomeStreams2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/maximize-website-earnings-ad-networks': {
      id: '/blog/maximize-website-earnings-ad-networks'
      path: '/blog/maximize-website-earnings-ad-networks'
      fullPath: '/blog/maximize-website-earnings-ad-networks'
      preLoaderRoute: typeof BlogMaximizeWebsiteEarningsAdNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/flipping-websites-beginners-guide': {
      id: '/blog/flipping-websites-beginners-guide'
      path: '/blog/flipping-websites-beginners-guide'
      fullPath: '/blog/flipping-websites-beginners-guide'
      preLoaderRoute: typeof BlogFlippingWebsitesBeginnersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogFlippingWebsitesBeginnersGuideRoute:
    BlogFlippingWebsitesBeginnersGuideRoute,
  BlogMaximizeWebsiteEarningsAdNetworksRoute:
    BlogMaximizeWebsiteEarningsAdNetworksRoute,
  BlogPassiveIncomeStreams2026Route: BlogPassiveIncomeStreams2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
